apiVersion: v1
kind: Secret
metadata:
  name: rabbit-secret
  namespace: "{{ .Values.namespace }}"
type: Opaque
stringData:
  adminUser: "{{ .Values.rabbit.adminUser | b64enc }}"
  adminPassword: "{{ .Values.rabbit.adminPassword | b64enc }}"

