apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: "{{ .Values.namespace }}"
  labels:
    app: rabbitmq
spec:
  type: "{{ .Values.service.type }}"
  ports:
  - name: amqp
    port: {{ .Values.service.ports.ss.port }}
    targetPort: {{ .Values.service.ports.ss.targetPort }}
    nodePort: {{ .Values.service.ports.ss.nodePort }}
  - name: management
    port: {{ .Values.service.ports.management.port }}
    targetPort: {{ .Values.service.ports.management.targetPort }}
    nodePort: {{ .Values.service.ports.management.nodePort }}

  selector:
    app: rabbitmq